/* Generated by scripts/generate-types.mjs from public/data/schema.json. Do not edit. */

/**
 * What a timing point along the race is anchored to.
 *
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "PointKind".
 */
export type PointKind = "start" | "distance" | "hurdle" | "touchdown" | "finish";

export interface SiteData {
  Index?: Index;
  EventData?: EventData;
  RaceData?: RaceData;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "Index".
 */
export interface Index {
  build: BuildOut;
  disciplines: DisciplineOut[];
  series: SeriesOut[];
  competitions: CompetitionOut[];
  formats: FormatOut[];
  checks: CheckOut[];
  annotations: AnnotationOut[];
  events: EventOut[];
  races: RaceSummary[];
  athletes: AthleteSummary[];
  athleteAliases: {
    [k: string]: string | undefined;
  };
  tables: TableOut[];
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "BuildOut".
 */
export interface BuildOut {
  builtAt: string;
  codeVersion: string;
  races: number;
  performances: number;
  athletes: number;
  splits: number;
  documents: number;
  flags: number;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "DisciplineOut".
 */
export interface DisciplineOut {
  id: string;
  name: string;
  shortName: string;
  kind: string;
  distance: number;
  barriers: {
    [k: string]: Barriers | undefined;
  };
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "Barriers".
 */
export interface Barriers {
  count: number;
  first: number;
  spacing: number;
  height: number;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "SeriesOut".
 */
export interface SeriesOut {
  id: string;
  name: string;
  shortName: string;
  kind: string;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "CompetitionOut".
 */
export interface CompetitionOut {
  id: string;
  name: string;
  series: string;
  startDate: string;
  endDate: string;
  venue: string;
  city: string;
  country: string;
  setting: string;
  resultsUrl: string | null;
  races: number;
  documents: number;
  declaredFile: string;
  declaredLine: number;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "FormatOut".
 */
export interface FormatOut {
  id: string;
  version: string;
  name: string;
  publisher: string;
  description: string;
  kind: string;
  module: string;
  documents: number;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "CheckOut".
 */
export interface CheckOut {
  id: string;
  group: string;
  severity: string;
  suspect: boolean;
  title: string;
  explanation: string;
  flags: number;
}
/**
 * What a mark printed beside results means (``TR16.8``: false start).
 *
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "AnnotationOut".
 */
export interface AnnotationOut {
  value: string;
  meaning: string;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "EventOut".
 */
export interface EventOut {
  id: string;
  discipline: string;
  sex: string;
  races: number;
  performances: number;
  athletes: number;
  withSplits: number;
  settings: string[];
  fastest: number | null;
  reaction?: number | null;
  shape?: Shape | null;
}
/**
 * How runners in an event typically spread their time over its distance (see
 * ``docs/replay-positions.md``): the replay moves runners this way between their splits.
 *
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "Shape".
 */
export interface Shape {
  points: ShapePoint[];
  runs: number;
  median: number;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "ShapePoint".
 */
export interface ShapePoint {
  distance: number;
  share: number;
  faster: number;
  slower: number;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "RaceSummary".
 */
export interface RaceSummary {
  id: string;
  competition: string;
  discipline: string;
  sex: string;
  event: string;
  round: string;
  heat: number | null;
  setting: string;
  date: string;
  title: string;
  athletes: number;
  winner: Winner | null;
  points: string[];
  formats: string[];
  flags: number;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "Winner".
 */
export interface Winner {
  athlete: string;
  time: number;
  records?: string[];
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "AthleteSummary".
 */
export interface AthleteSummary {
  id: string;
  number: number;
  formerNumbers: number[];
  name: string;
  givenName: string;
  familyName: string;
  country: string;
  sex: string;
  birthDate: string | null;
  races: number;
  events: string[];
  bests: {
    [k: string]: number | undefined;
  };
  worldAthleticsUrl: string | null;
}
/**
 * A table of the downloadable database.
 *
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "TableOut".
 */
export interface TableOut {
  name: string;
  description: string;
  rows: number;
  columns: ColumnOut[];
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "ColumnOut".
 */
export interface ColumnOut {
  name: string;
  type: string;
  description: string;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "EventData".
 */
export interface EventData {
  event: string;
  discipline: string;
  sex: string;
  points: Point[];
  performances: EventPerformance[];
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "Point".
 */
export interface Point {
  key: string;
  kind: PointKind;
  distance: number;
  hurdle: number | null;
  label: string;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "EventPerformance".
 */
export interface EventPerformance {
  id: string;
  race: string;
  athlete: string;
  place: number | null;
  status: string;
  time: number | null;
  format: string | null;
  splits: (number | null)[];
  suspect: number[];
  reaction?: number | null;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "RaceData".
 */
export interface RaceData {
  id: string;
  competition: string;
  discipline: string;
  sex: string;
  round: string;
  heat: number | null;
  setting: string;
  title: SStr;
  date: SStr;
  startTime: SStr | null;
  wind: SNum | null;
  temperature: SNum | null;
  humidity: SNum | null;
  weather: SStr | null;
  documents: DocumentOut[];
  points: Point[];
  performances: RacePerformance[];
  flags: FlagOut[];
  sources: Source[];
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "SStr".
 */
export interface SStr {
  v: string;
  s: number;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "SNum".
 */
export interface SNum {
  v: number;
  s: number;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "DocumentOut".
 */
export interface DocumentOut {
  id: string;
  format: string;
  formatVersion: string;
  title: string;
  url: string;
  archiveUrl: string | null;
  sha256: string;
  size: number;
  retrievedAt: string;
  retrievedFrom: string;
  pages: number;
  issued: SStr | null;
  revision: SStr | null;
  timingBy: SStr | null;
  declaredFile: string;
  declaredLine: number;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "RacePerformance".
 */
export interface RacePerformance {
  id: string;
  athlete: string;
  name: SStr;
  givenName: string;
  familyName: string;
  country: SStr | null;
  birthDate: SStr | null;
  bib: SStr | null;
  lane: SInt | null;
  place: SInt | null;
  status: string;
  time: SNum | null;
  resultSource: number;
  reactionTime: SNum | null;
  preciseTime: SNum | null;
  qualification: SStr | null;
  records: SStr[];
  remarks: SStr[];
  splits: RaceSplit[];
  segments: RaceSegment[];
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "SInt".
 */
export interface SInt {
  v: number;
  s: number;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "RaceSplit".
 */
export interface RaceSplit {
  doc: number;
  point: number;
  time: SNum;
  rank: SInt | null;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "RaceSegment".
 */
export interface RaceSegment {
  doc: number;
  start: number | null;
  end: number;
  time: SNum;
}
/**
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "FlagOut".
 */
export interface FlagOut {
  check: string;
  severity: string;
  subject: string;
  field: string | null;
  message: string;
  suspect: boolean;
  sources: number[];
}
/**
 * Where a value came from: a box on a document page, or a line of the catalog.
 *
 * This interface was referenced by `SiteData`'s JSON-Schema
 * via the `definition` "Source".
 */
export interface Source {
  doc: number | null;
  page: number | null;
  box: [number, number, number, number] | null;
  text: string | null;
  method: string;
  file: string | null;
  line: number | null;
}
